### ISSUE TITLE
what is a line?

### ISSUE THREAD

**Issue by sanette** [hummy123/ocaml-piecerope#4]
Thanks for this library! I think you should define what a line is for you. Given a single "line", the stats return "number of lines=0". This is not intuitive:
```ocaml
# let r = Piece_rope.of_string "Bonjour";;
# Piece_rope.stats r;;
- : Piece_rope__Piece_types.tree_stats =
{Piece_rope__.Piece_types.lines = 0; utf32_length = 7; utf16_length = 7;
 utf8_length = 7}
```

**Comment by hummy123** [comment]
@sanette I implemented your feedback which was a simple change and it reminded me that I needed to handle \r\n line breaks properly (it only worked properly for \r and \n line breaks before but now it works for \r\n as well). Also updated the piece_rope.mli docs (just for insert, delete, substring and get_line) to inform about these changes.

Thanks again for your feedback and helping make this library better. The updated version should be available on opam after the opam maintainers review it.
https://github.com/ocaml/opam-repository/pull/23559
